version: '3'

interval: 500ms

tasks:
  dev:
    desc: Run the UFO Gateway in development mode with hot reload
    watch: true
    sources:
      - cmd/**/*.go
      - internal/**/*.go
    deps:
      - build
    cmds:
      - ./dist/ufogateway

  build:
    desc: Build the UFO Gateway
    cmds:
      - go build -o ./dist/ufogateway ./cmd/ufogateway/main.go
      - chmod +x ./dist/ufogateway

  fixperms:
    desc: Fix project file permissions
    cmd: chmod 777 -R .